-- Current public offers only.
-- Run this in Supabase SQL editor if the website reads products from the products table.

insert into public.products (
  id,
  brand_id,
  brand_en,
  brand_ar,
  name_en,
  name_ar,
  category,
  catalog_group,
  size,
  quantity,
  price,
  original_price,
  pricing_mode,
  is_purchasable,
  image_url,
  description_en,
  description_ar,
  in_stock,
  is_published,
  catalog_order,
  image_type,
  image_fit
)
values
  (
    'offer-adhari-330-15-plus-5',
    'adhari',
    'Adhari',
    'عذاري',
    'Adhari 330ml 15 + 5 Cartons Offer',
    'عرض مياه عذاري 330 مل 15 + 5 كراتين',
    'offer',
    '330ml',
    '330ml',
    20,
    199,
    265,
    'fixed',
    true,
    '/images/offers/adhari-campaign.png',
    'Buy 15 Adhari 330ml cartons and get 5 cartons free for SAR 199, including VAT and delivery in Riyadh.',
    'اشتر 15 كرتون مياه عذاري 330 مل واحصل على 5 كراتين مجانا بسعر 199 ريال شامل الضريبة والتوصيل داخل الرياض.',
    true,
    true,
    0,
    'offer',
    'balanced'
  ),
  (
    'offer-aghadeer-330-15-plus-5',
    'agadir',
    'Agadir',
    'أغادير',
    'Aghadeer 330ml 15 + 5 Cartons Offer',
    'عرض مياه أغادير 330 مل 15 + 5 كراتين',
    'offer',
    '330ml',
    '330ml',
    20,
    195,
    260,
    'fixed',
    true,
    '/images/offers/aghadeer-campaign.jpeg',
    'Buy 15 Aghadeer 330ml cartons and get 5 cartons free for SAR 195, including VAT and delivery in Riyadh.',
    'اشتر 15 كرتون مياه أغادير 330 مل واحصل على 5 كراتين مجانا بسعر 195 ريال شامل الضريبة والتوصيل داخل الرياض.',
    true,
    true,
    1,
    'offer',
    'balanced'
  ),
  (
    'offer-naqi-200-15-plus-5',
    'naqi',
    'Naqi',
    'نقي',
    'Naqi 200ml 15 + 5 Cartons Offer',
    'عرض مياه نقي 200 مل 15 + 5 كراتين',
    'offer',
    '200ml',
    '200ml',
    20,
    199,
    265,
    'fixed',
    true,
    '/images/offers/naqi-campaign.jpeg',
    'Buy 15 Naqi 200ml cartons and get 5 cartons free for SAR 199, including VAT and delivery in Riyadh.',
    'اشتر 15 كرتون مياه نقي 200 مل واحصل على 5 كراتين مجانا بسعر 199 ريال شامل الضريبة والتوصيل داخل الرياض.',
    true,
    true,
    2,
    'offer',
    'balanced'
  ),
  (
    'offer-nova-330-15-plus-5',
    'nova',
    'Nova',
    'نوفا',
    'Nova 330ml 15 + 5 Cartons Offer',
    'عرض مياه نوفا 330 مل 15 + 5 كراتين',
    'offer',
    '330ml',
    '330ml',
    20,
    350,
    467,
    'fixed',
    true,
    '/images/offers/nova-campaign.png',
    'Buy 15 Nova 330ml cartons and get 5 cartons free for SAR 350, including VAT and delivery in Riyadh.',
    'اشتر 15 كرتون مياه نوفا 330 مل واحصل على 5 كراتين مجانا بسعر 350 ريال شامل الضريبة والتوصيل داخل الرياض.',
    true,
    true,
    3,
    'offer',
    'balanced'
  ),
  (
    'offer-oubi-330-15-plus-5',
    'oubi',
    'Oubi',
    'أوبي',
    'Oubi 330ml 15 + 5 Cartons Offer',
    'عرض مياه أوبي 330 مل 15 + 5 كراتين',
    'offer',
    '330ml',
    '330ml',
    20,
    209,
    280,
    'fixed',
    true,
    '/images/offers/oubi-campaign.jpeg',
    'Buy 15 Oubi 330ml cartons and get 5 cartons free for SAR 209, including VAT and delivery in Riyadh.',
    'اشتر 15 كرتون مياه أوبي 330 مل واحصل على 5 كراتين مجانا بسعر 209 ريال شامل الضريبة والتوصيل داخل الرياض.',
    true,
    true,
    4,
    'offer',
    'balanced'
  )
on conflict (id) do update set
  brand_id = excluded.brand_id,
  brand_en = excluded.brand_en,
  brand_ar = excluded.brand_ar,
  name_en = excluded.name_en,
  name_ar = excluded.name_ar,
  category = excluded.category,
  catalog_group = excluded.catalog_group,
  size = excluded.size,
  quantity = excluded.quantity,
  price = excluded.price,
  original_price = excluded.original_price,
  pricing_mode = excluded.pricing_mode,
  is_purchasable = excluded.is_purchasable,
  image_url = excluded.image_url,
  description_en = excluded.description_en,
  description_ar = excluded.description_ar,
  in_stock = excluded.in_stock,
  is_published = excluded.is_published,
  catalog_order = excluded.catalog_order,
  image_type = excluded.image_type,
  image_fit = excluded.image_fit;

update public.products
set is_published = false
where id in ('offer-fly-15-plus-5', 'offer-fly-330-15-plus-5');
